### ISSUE TITLE
Need a better process in MINT to submit proposals.

### ISSUE THREAD

**Issue by pbsa-github** [peerplays-network/bos-mint#26]
Right now there are too many steps required to submit proposals, which for some witnesses is a prohibitive issue when there are occasions with many proposals required.

From @bitcoinsig

> Bitcoinsig, [Jan 28, 2020 at 2:37:51 PM]:
...It takes too many clicks and going to too many other websites to collate the data. For example, for me I have to fire up an ssh connection to mint, then check on sofies site to see what games have expired, then view the incidents, then check google to verify the incident reports, then go back to mint and find the game ,then I have to dig through game IDs, teams, etc and finally make 20+clicks to resolve a soccer game, then finally approve my own proposal and broadcast it here. I simply cannot easily do all that from my mobile either as I would need to switch back and forth between applications/webpages so it would take even longer. So basically unless I'm on a real laptop/desktop I generally have to wait to respond to any proposal announcement here.
> 

From @blockops1

> ... the review of each proposal takes almost as long as creating a proposal. Is it possible to put more information into each of the proposals, like date, time,  @teams, score so that review goes quicker?

>

**Comment by jemshid** [comment]
in_progress to finished script done. To be tested and git committed.

**Comment by jemshid** [comment]
Working on finished to settled.

**Comment by jemshid** [comment]
Script for resolving all betting groups in one shot from scores sent for testing.

**Comment by jemshid** [comment]
Working on adding team names along with proposal in the MINT dashboard.

**Comment by jemshid** [comment]
[](https://github.com/peerplays-network/bos-utils/tree/master/mint_auto)
The script given here takes care of moving an event from
1. upcoming to in_progress
2. in_progress to finished
3. finished to settled.

**Comment by jemshid** [comment]
https://github.com/peerplays-network/bos-mint/pull/31

This PR takes care of displaying the following details in pending proposals page.
1. Details of the event which includes event start timestamp and score
2. Team names along with betting markets.

**Comment by belakon1975** [comment]
@jemshid  please estimate!  For Example (XS) Need a better process in MINT to submit proposals.  

(XXS- 0.5 days
XS- 1 day
S- 2 days
M-3 days
L- 5 days
XL 8 days
XXL 13 days)

**Comment by belakon1975** [comment]
@jemshid  please estimate this ticket !
