### ISSUE TITLE
Display relevant information with each proposal to make review quicker.

### ISSUE THREAD

**Issue by jemshid** [peerplays-network/bos-mint#29]
Display date, time, teams and score along with proposals in MINT so that review goes quicker.

**Comment by belakon1975** [comment]
please estimate! XXS- 0.5 days, XS -1 day, S- 2 days, M- 3 days, L 5-days , XL- 8 days, XXL- 13 days

**Comment by jemshid** [comment]
@belakon1975 the issue is solved. Moving it to done.
